on:
  push:
    branches:
      - main

name: Build Hospital Management App

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Determine Next Version
        id: next_version
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        run: |
          npm install semver
          echo ::set-output name=next_version::$(semver inc "${{ github.ref_name }}" minor)

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: ${{ steps.next_version.outputs.next_version }}
          token: ${{ secrets.TOKEN }}